[providers]
   [providers.file]

[http.routers]
  [http.routers.router1]
    Service = "service1"
    Rule = "Host(`localhost`)"

[http.services]
 [http.services.service1]
   [http.services.service1.LoadBalancer]

     [[http.services.service1.LoadBalancer.Servers]]
       URL = "http://127.0.0.1:2000"
       Weight = 1